FROM maven:3.9-eclipse-temurin-1* AS build

WORKDIR /app

COPY . .
*RUN mvn clean package -DskipTests
*FROM eclipse-temurin:17-jre

WORKD*R /app

COPY --from=build /app/tar*et/*.jar app.jar

EXPOSE 8081

CMD*["java","-jar","app.jar"]