FROM maven:3.*-eclipse-temurin-17 AS build

WORK*IR /app

COPY . .

RUN mvn clean p*ckage -DskipTests

FROM eclipse-te*urin:17-jre

WORKDIR /app

COPY --*rom*build /app/target/*.jar app.jar

E*POSE 8080

CMD ["java", "-jar", "a*p.jar"]