spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enterprisehub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: enterprisehub
    password: enterprisehub
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false