spring:
  datasource:
    url: ${DB_URL}
    # jdbc:mysql://localhost:3306/enterprisehub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER} 
    # enterprisehub
    password: ${DB_PASSWORD}
    # enterprisehub
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false