package com.enterprisehub.service;
import com.enterprisehub.domain.*; import com.enterprisehub.repo.*; import jakarta.persistence.EntityNotFoundException; import jakarta.persistence.criteria.JoinType; import java.time.Instant; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class RequestService {
 private final ServiceRequestRepository requests; private final EmployeeRepository employees; private final DepartmentRepository departments; private final AuditRepository audits; private final JdbcTemplate jdbc;
 public RequestService(ServiceRequestRepository r,EmployeeRepository e,DepartmentRepository d,AuditRepository a,JdbcTemplate j){requests=r;employees=e;departments=d;audits=a;jdbc=j;}
 public Page<ServiceRequest> list(String q,String status,String priority,int page,int size){Specification<ServiceRequest>s=(root,query,cb)->cb.conjunction(); if(q!=null&&!q.isBlank())s=s.and((r,x,c)->c.or(c.like(c.lower(r.get("title")),"%"+q.toLowerCase()+"%"),c.like(c.lower(r.get("description")),"%"+q.toLowerCase()+"%"))); if(status!=null&&!status.isBlank())s=s.and((r,x,c)->c.equal(r.get("status"),status)); if(priority!=null&&!priority.isBlank())s=s.and((r,x,c)->c.equal(r.get("priority"),priority)); var result=requests.findAll(s,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by("createdAt").descending())); result.forEach(this::updateSlaView);return result;}
 public Page<ServiceRequest> list(String q,String status,String priority,int page,int size,String email){var employee=user(email);if(!employee.role.equals("ADMIN")&&!employee.role.equals("MANAGER")){Specification<ServiceRequest>s=(r,x,c)->c.or(c.equal(r.get("requester").get("id"),employee.id),c.equal(r.get("assignee").get("id"),employee.id));if(q!=null&&!q.isBlank())s=s.and((r,x,c)->c.or(c.like(c.lower(r.get("title")),"%"+q.toLowerCase()+"%"),c.like(c.lower(r.get("description")),"%"+q.toLowerCase()+"%")));if(status!=null&&!status.isBlank())s=s.and((r,x,c)->c.equal(r.get("status"),status));if(priority!=null&&!priority.isBlank())s=s.and((r,x,c)->c.equal(r.get("priority"),priority));var p=requests.findAll(s,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by("createdAt").descending()));p.forEach(this::updateSlaView);return p;}return list(q,status,priority,page,size);}
 public ServiceRequest getAccessible(Long id,String email){var r=requests.findById(id).orElseThrow(()->new EntityNotFoundException("Request not found"));var e=user(email);if(!e.role.equals("ADMIN")&&!e.role.equals("MANAGER")&&!java.util.Objects.equals(r.requester.id,e.id)&&(r.assignee==null||!java.util.Objects.equals(r.assignee.id,e.id)))throw new org.springframework.security.access.AccessDeniedException("You can only view requests you submitted or are assigned to");updateSlaView(r);return r;}
 public java.util.List<AuditLog> auditAccessible(Long id,String email){getAccessible(id,email);return audits.findByRequestIdOrderByCreatedAtDesc(id);}
 private void updateSlaView(ServiceRequest r){Instant now=Instant.now();if(r.slaDueAt==null){r.slaStatus=r.resolvedAt==null?"ON_TRACK":"COMPLETED";r.slaRemainingSeconds=null;return;}Instant start=r.createdAt==null?r.slaDueAt.minusSeconds(slaSeconds(r.priority)):r.createdAt;r.slaStatus=slaStatus(start,r.slaDueAt,now,r.resolvedAt!=null);r.slaRemainingSeconds=r.resolvedAt!=null?0L:Math.max(0,java.time.Duration.between(now,r.slaDueAt).getSeconds());}
 public static String slaStatus(Instant created,Instant deadline,Instant now,boolean completed){if(completed)return "COMPLETED";if(deadline==null)return "ON_TRACK";long remaining=java.time.Duration.between(now,deadline).getSeconds();if(remaining<=0)return "BREACHED";long total=Math.max(0,java.time.Duration.between(created,deadline).getSeconds());return remaining<=total/5?"AT_RISK":"ON_TRACK";}
 public static String priorityFor(String impact,String urgency){int i=level(impact),u=level(urgency);if(i>=4&&u>=3||i>=3&&u>=4)return "P1";if(i>=3&&u>=2||i>=2&&u>=3)return "P2";if(i>=2||u>=2)return "P3";return "P4";} private static int level(String v){return switch(v.toUpperCase()){case "CRITICAL"->4;case "HIGH"->3;case "MEDIUM"->2;default->1;};} public static long slaSeconds(String p){return switch(p){case "P1"->14400L;case "P2"->28800L;case "P3"->86400L;default->259200L;};} private static String reasonFor(String impact,String urgency,String p){return p+" assigned from "+impact.toLowerCase()+" impact and "+urgency.toLowerCase()+" urgency";}
 @Transactional public ServiceRequest create(java.util.Map<String,Object> body,String email){return create(body,email,null);}
 @Transactional public ServiceRequest create(java.util.Map<String,Object> body,String email,String key){var u=user(email);if(key!=null&&!key.isBlank()){if(key.length()>140)throw new IllegalArgumentException("Idempotency-Key must be 140 characters or fewer");String scoped=u.id+":"+key;var prior=requests.findByIdempotencyKey(scoped);if(prior.isPresent())return prior.get();}
var d=departments.findById(Long.valueOf(body.get("departmentId").toString())).orElseThrow();var r=new ServiceRequest();r.title=body.get("title").toString();r.description=body.get("description").toString();r.category=body.getOrDefault("category","Other").toString();r.impact=body.getOrDefault("impact","MEDIUM").toString().toUpperCase();r.urgency=body.getOrDefault("urgency","MEDIUM").toString().toUpperCase();r.priority=priorityFor(r.impact,r.urgency);r.priorityReason=reasonFor(r.impact,r.urgency,r.priority);r.status="PENDING_APPROVAL";r.requester=u;r.department=d;if(key!=null&&!key.isBlank())r.idempotencyKey=u.id+":"+key;r.slaDueAt=Instant.now().plusSeconds(slaSeconds(r.priority));r.dueAt=r.slaDueAt;var saved=requests.save(r);audits.save(new AuditLog(saved,u,"CREATED",null,saved.status,"Request created; "+r.priorityReason));return saved;}
 private Employee user(String email){return employees.findByEmail(email).orElseThrow(()->new EntityNotFoundException("Employee not found"));}
 @Transactional public ServiceRequest action(Long id,String action,String assigneeEmail,String actorEmail,String reason){var r=requests.findById(id).orElseThrow(()->new EntityNotFoundException("Request not found"));var actor=user(actorEmail);String role=actor.role;String old=r.status;switch(action){case "approve"->{if(!role.equals("MANAGER")&&!role.equals("ADMIN"))throw new org.springframework.security.access.AccessDeniedException("Manager approval required");if(!r.status.equals("PENDING_APPROVAL"))throw new IllegalArgumentException("Only pending requests can be approved");r.status="OPEN";}case "reject"->{if(!role.equals("MANAGER")&&!role.equals("ADMIN"))throw new org.springframework.security.access.AccessDeniedException("Manager approval required");if(!r.status.equals("PENDING_APPROVAL"))throw new IllegalArgumentException("Only pending requests can be rejected");r.status="REJECTED";}case "assign"->{if(!role.equals("ADMIN")&&!role.equals("MANAGER"))throw new org.springframework.security.access.AccessDeniedException("Manager access required");if(!r.status.equals("OPEN")&&!r.status.equals("IN_PROGRESS"))throw new IllegalArgumentException("Only open requests can be assigned");r.assignee=user(assigneeEmail);r.status="IN_PROGRESS";}case "resolve"->{if(!r.status.equals("IN_PROGRESS"))throw new IllegalArgumentException("Only in-progress requests can be resolved");if(!role.equals("ADMIN")&&!role.equals("MANAGER")&&(r.assignee==null||!java.util.Objects.equals(r.assignee.id,actor.id)))throw new org.springframework.security.access.AccessDeniedException("Only the assignee or a manager can resolve");r.status="RESOLVED";r.resolvedAt=Instant.now();r.resolutionSeconds=Math.max(0,java.time.Duration.between(r.createdAt==null?r.resolvedAt:r.createdAt,r.resolvedAt).getSeconds());r.resolvedOnTime=r.slaDueAt!=null&&!r.resolvedAt.isAfter(r.slaDueAt);}default->throw new IllegalArgumentException("Unknown action");}var saved=requests.save(r);audits.save(new AuditLog(r,actor,"STATUS_CHANGED",old,r.status,(reason==null||reason.isBlank()?"Workflow action: "+action:reason.trim())));return saved;}
 @Transactional public ServiceRequest overridePriority(Long id,String impact,String urgency,String reason,String actorEmail){var r=requests.findById(id).orElseThrow(()->new EntityNotFoundException("Request not found"));var actor=user(actorEmail);if(!actor.role.equals("MANAGER")&&!actor.role.equals("ADMIN"))throw new org.springframework.security.access.AccessDeniedException("Only managers and admins can override priority");if(reason==null||reason.isBlank())throw new IllegalArgumentException("A reason is required for priority overrides");String old=r.priority;String next=priorityFor(impact,urgency);r.impact=impact.toUpperCase();r.urgency=urgency.toUpperCase();r.priority=next;r.priorityReason="Manually overridden: "+reason.trim();if(r.resolvedAt==null){r.slaDueAt=(r.createdAt==null?Instant.now():r.createdAt).plusSeconds(slaSeconds(next));r.dueAt=r.slaDueAt;}var saved=requests.save(r);audits.save(new AuditLog(r,actor,"PRIORITY_OVERRIDE",old,next,reason.trim()));return saved;}
 public java.util.Map<String,Object> analytics(){var m=new java.util.HashMap<String,Object>(jdbc.queryForMap("SELECT COALESCE(SUM(CASE WHEN status NOT IN ('RESOLVED','REJECTED') THEN 1 ELSE 0 END),0) open_requests, COALESCE(SUM(CASE WHEN priority='P1' AND status NOT IN ('RESOLVED','REJECTED') THEN 1 ELSE 0 END),0) critical_requests, COALESCE(SUM(CASE WHEN resolved_at IS NULL AND sla_due_at>NOW() AND TIMESTAMPDIFF(SECOND,NOW(),sla_due_at)<=TIMESTAMPDIFF(SECOND,created_at,sla_due_at)*0.2 AND status NOT IN ('RESOLVED','REJECTED') THEN 1 ELSE 0 END),0) at_risk_requests, COALESCE(SUM(CASE WHEN resolved_at IS NULL AND sla_due_at<NOW() AND status NOT IN ('RESOLVED','REJECTED') THEN 1 ELSE 0 END),0) breached_requests, AVG(CASE WHEN resolved_at IS NOT NULL THEN resolution_seconds END) average_resolution_seconds FROM service_requests"));m.put("byStatus",jdbc.queryForList("SELECT status,COUNT(*) total FROM service_requests GROUP BY status"));return m;}
 public java.util.List<AuditLog> audit(Long id){return audits.findByRequestIdOrderByCreatedAtDesc(id);}
}
