package com.enterprisehub.security;
import com.fasterxml.jackson.databind.ObjectMapper; import java.io.IOException; import java.util.List; import java.util.Map; import org.springframework.context.annotation.*; import org.springframework.http.HttpStatus; import org.springframework.http.MediaType; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.security.web.AuthenticationEntryPoint; import org.springframework.security.web.access.AccessDeniedHandler; import org.springframework.web.cors.*;
@Configuration @org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean AuthenticationEntryPoint apiAuthenticationEntryPoint(ObjectMapper mapper){return (request,response,error)->write(response,mapper,HttpStatus.UNAUTHORIZED,"UNAUTHENTICATED","Authentication is required");}
 @Bean AccessDeniedHandler apiAccessDeniedHandler(ObjectMapper mapper){return (request,response,error)->write(response,mapper,HttpStatus.FORBIDDEN,"FORBIDDEN","You do not have permission to perform this action");}
 private static void write(jakarta.servlet.http.HttpServletResponse response,ObjectMapper mapper,HttpStatus status,String code,String message)throws IOException{response.setStatus(status.value());response.setContentType(MediaType.APPLICATION_JSON_VALUE);mapper.writeValue(response.getOutputStream(),Map.of("error",message,"code",code));}
 @Bean SecurityFilterChain chain(HttpSecurity http,JwtFilter filter,AuthenticationEntryPoint apiAuthenticationEntryPoint,AccessDeniedHandler apiAccessDeniedHandler)throws Exception{return http.csrf(c->c.disable()).cors(c->c.configurationSource(r->{var x=new CorsConfiguration();x.setAllowedOrigins(List.of("http://localhost:5173"));x.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));x.setAllowedHeaders(List.of("*"));x.setAllowCredentials(true);return x;})).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint(apiAuthenticationEntryPoint).accessDeniedHandler(apiAccessDeniedHandler)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/**","/v3/api-docs/**","/swagger-ui/**","/swagger-ui.html","/actuator/health").permitAll().anyRequest().authenticated()).addFilterBefore(filter,UsernamePasswordAuthenticationFilter.class).build();}
}
